# Generated by Django 2.2 on 2020-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200518_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-shirts'), ('SR', 'Sharee'), ('T', 'Tops')], max_length=2),
        ),
    ]
