# Generated by Django 2.2 on 2020-05-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200513_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description added'),
            preserve_default=False,
        ),
    ]
